name: Just testing

on:
  workflow_dispatch:
    
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout Code
        uses: actions/checkout@v3.1.0
        
      - name: Test
        run: make unit
